blog/urls.py
from django.conf.urls import url
from blog.views import index, archive, tag, category, article, comment_post, do_logout, do_login, do_reg
from django.conf import settings

urlpatterns = [
    url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'^archive/upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'^tag/upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^category/$', category, name='category'),
    url(r'^article/$', article, name='article'),
    url(r'^archive/$', archive, name='archive'),
    url(r'^tag/$', tag, name='tag'),
    url(r'^login/$', do_login, name='login'),
    url(r'^reg/$', do_reg, name='reg'),
    url(r'^logout/$', do_logout, name='logout'),
    url(r'^comment_post/$', comment_post, name='comment_post'),
    url(r'^$', index, name='index'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.upload import upload_image
from blog import urls

urlpatterns = [
    url(r'^admin/upload/(?P<dir_name>.*)$', upload_image, name='upload_image'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(urls, namespace='blog'))
]

templates/ad.html
{% load staticfiles %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner">
            <!--
            <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" /></a>
            -->
            {% for ad in ad_list %}
            <a href="/" target="_blank"><img id={{ ad.id }} src="upload/{{ ad.image_url }}"  alt="" /></a>
            {% endfor %}

          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

    /*
    var num = 0;
    {% for ad in ad_list %}
    slider.data += [{
        "id":"{{ ad.id }}",
        "client":"{{ ad.title }}",
        "desc":"{{ ad.description }}",
    },];
    {% endfor %} */


    /*
    slider.data = [{
        "id":"1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },]; */



  slider.data= [
    {
        "id":"1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },
    {
        "id":"2",
        "client":"标题2",
        "desc":"add your description hereaaaa"
    },
    {
        "id":"slide-img-3",
        "client":"标题3",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-4",
        "client":"标题4",
        "desc":"add your description here"
    }
  ];


    </script>
    </div>
    <!-- banner代码 结束 -->

templates/ad_bak.html
{% load staticfiles %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner">
            <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" /></a>
            <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" /></a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

  slider.data= [
    {
        "id":"slide-img-1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },
    {
        "id":"slide-img-2",
        "client":"标题2",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-3",
        "client":"标题3",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-4",
        "client":"标题4",
        "desc":"add your description here"
    }
  ];

    </script>
    </div>
    <!-- banner代码 结束 -->

templates/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ request.GET.year }}/{{ request.GET.month }}文章归档</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load myfilter %}
{% block left_content %}
    <div class="postdate">
      <div class="month">{{ article.date_publish | month_to_upper }}</div>
      <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
{#          {{ article.content | safe }}#}
            {% autoescape off %}
                {{ article.content }}
            {% endautoescape %}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <div class="info">
        Address:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>

      <div class="commentstitle"><h3 id="comments"><span class="commentsnumber">only {{ comment_list.count }} comment</span> untill now</h3></div>

      <ol class="commentlist">
          {% for comment in comment_list %}
          <li id="comment-59418">
                <div class="top"><a href='{{ comment.url }}' rel='external nofollow' class='url'>{{ comment.username }}</a><span class="time"> @ <a href="#comment-59418" title="">{{ comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                <div><img alt='' src='{% static 'images/default.jpg' %}' class='avatar avatar-32 photo' height='32' width='32' /></div>

                <div class="body">
                                <p>{{ comment.content }}</p>
                </div>
          </li>
          {% for children_comment in comment.children_comment %}
          <li id="comment-59542">
                <div class="reply">
                  <div class="top"><a href="{{ children_comment.url }}" rel="external nofollow" class="url">{{ children_comment.username }}</a><span class="time"> @ <a href="#comment-59543" title="">{{ children_comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                  <div><img alt="" src="{% static 'images/default.jpg' %}" class="avatar avatar-32 photo" height="32" width="32"></div>

                  <div class="body">
                                        {{ children_comment.content }}                  </div>
                </div>
          </li>
          {% endfor %}
          {% endfor %}
      </ol>


    <div id="commentform">
    <h3 id="respond">Add your comment now</h3>
    {% if not request.user.is_authenticated %}
    <div class='login_info'>还没有登陆？可以登录后再评论哦。<b><a href="{% url 'blog:login' %}">&raquo;去登录</a>&nbsp;<a href="{% url 'blog:reg' %}">&raquo;去注册</a></b></div>
    {% else %}
    <div class='login_info'><b>{{ request.user.username }}</b>,快来写点评论吧!&nbsp;<a href="{% url 'blog:logout' %}">注销</a></div>
    {% endif %}


    <form action="{% url 'blog:comment_post' %}" method="post">
    {% csrf_token %}
    <p>{{ comment_form.author }}
    <label for="author">Name (required)</label></p>

    <p>{{ comment_form.email }}
    <label for="email">Email (Will NOT be published) (required)</label></p>

    <p>{{ comment_form.url }}
    <label for="url">URL</label></p>


    <!--<p><small><strong>XHTML:</strong> You can use these tags: &lt;a href=&quot;&quot; title=&quot;&quot;&gt; &lt;abbr title=&quot;&quot;&gt; &lt;acronym title=&quot;&quot;&gt; &lt;b&gt; &lt;blockquote cite=&quot;&quot;&gt; &lt;cite&gt; &lt;code class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;del datetime=&quot;&quot;&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=&quot;&quot;&gt; &lt;strike&gt; &lt;strong&gt; &lt;pre class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;span class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; </small></p>-->

    <p>{{ comment_form.comment }}</p>

    <p>
        {{ comment_form.article }}
        <input name="submit" type="submit" id="submit" tabindex="5" value="Submit" class="button" />
    </p>
    </form>
    </div>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ SITE_NAME }}</title>
<meta name="keywords" content="{{ SITE_NAME }}" />
<meta name="description" content="{{ SITE_DESC }}" />
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% block custom_css %}{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
{% block custom_js %}{% endblock %}
</head>
<body>
<header>
  <div class="logo">
      <h1>{{ SITE_NAME }}</h1>
      <p>{{ SITE_DESC }}</p>
  </div>
  <nav id="topnav" class="f_r">
    <ul>
      <a href="/">首页</a>
      {% for category in category_list %}
      <a href="{% url 'blog:category' %}?cid={{ category.id }}">{{ category.name }}</a>
      {% endfor %}
    </ul>
    <script src="{% static 'js/nav.js' %}"></script>
  </nav>
</header>
<article>
  <div class="l_box f_l">
      {% block left_content %}{% endblock %}
  </div>
  <div class="r_box f_r">
    <div class="tit01">
      <h3>关注我</h3>
      <div class="gzwm">
        <ul>
          <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
          <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
          <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
          <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
        </ul>
      </div>
    </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
      <script>
        window.onload = function ()
        {
          var oLi = document.getElementById("tab").getElementsByTagName("li");
          var oUl = document.getElementById("ms-main").getElementsByTagName("div");

          for(var i = 0; i < oLi.length; i++)
          {
            oLi[i].index = i;
            oLi[i].onmouseover = function ()
            {
              for(var n = 0; n < oLi.length; n++) oLi[n].className="";
              this.className = "cur";
              for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
              oUl[this.index].style.display = "block"
            }
          }
        }
      </script>
      <div class="ms-top">
        <ul class="hd" id="tab">
          <li class="cur"><a href="/">浏览排行</a></li>
          <li><a href="/">评论排行</a></li>
          <li><a href="/">站长推荐</a></li>
        </ul>
      </div>
      <div class="ms-main" id="ms-main">
        <div style="display: block;" class="bd bd-news" >
          <ul>
              {% for article in article_click_list %}
              <li><a href="/" target="_blank">{{ article.title | slice:':15' }}</a></li>
              {% endfor %}
          </ul>
        </div>
        <div  class="bd bd-news">
          <ul>
            {% for article in article_comment_list %}
            <li><a href="/" target="_blank">{{ article.title | slice:':15' }}</a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="bd bd-news">
          <ul>
              {% for article in article_is_recommend %}
                  <li><a href="/" target="_blank">{{ article.title }}</a></li>
              {% endfor %}
          </ul>
        </div>
      </div>
      <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
      <h3>标签云</h3>
      <ul>
          {% for tag in tag_list %}
              <li><a href="{% url 'blog:tag' %}?tag_name={{ tag.name }}">{{ tag.name }}</a> </li>
          {% endfor %}
      </ul>
    </div>
    <div class="tuwen">
      <h3>文章归档</h3>
      <ul>
        {% for archive in archive_list %}
        <li>
          <p><span class="tutime font-size-18"><a href='{% url 'blog:archive' %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}'>{{ archive }}</a></span></p>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="links">
      <h3>友情链接</h3>
      <ul>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
      </ul>
    </div>
  </div>
  <!--r_box end -->
</article>
<footer>
  <p class="ft-copyright">某某某的个人博客 蜀ICP备xxxxxxx号-1</p>
  <div id="tbox"> <a id="togbook" href="/">a</a> <a id="gotop" href="javascript:void(0)">b</a> </div>
</footer>
</body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ category.name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/failure.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作失败</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
    <style type="text/css">
        ul li{float: left; margin-left: 10px;}
    </style>
</head>

<body>
<div class="microoh-main" style="height: 150px">
    <div class="container" style="position: absolute; top: 20px; left: 20px;">
        <div style="height: 150px">
            <i class="v5-icon v5-icon-wrong"></i>
            <span>{{ reason | safe }}</span>
        </div>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>最新文章</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'blog:article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/login.html

{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
			<form action="{% url 'blog:login' %}" method="post">
                {% csrf_token %}
				<ul class="right-form">
					<h2>Login:</h2>
					<li>
                       <!-- <input type="text" name="username" placeholder="Username" required/> -->
                        {{ login_form.username }}
                    </li>
					<li>
                       <!-- <input type="password" name="password" placeholder="Password" required/> -->
                        {{ login_form.password }}
                    </li>
					<input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
                    <input type="submit" value="Login" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>

			</form>
	</div>
</body>
</html>

templates/pagination.html
<div id="pagination">
    <ul id="pagination-flickr">
    {% if article_list.has_previous %}
    <li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.tag_name %}&tag_name={{ request.GET.tag_name }}{% endif %}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}
     <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
    {% if article_list.has_next %}
      <li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.tag_name %}&tag_name={{ request.GET.tag_name }}{% endif %}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

templates/reg.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Create a Free Account!</h1>
		</div>
		<p></p>
			<form action="{% url 'blog:reg' %}" method="post">
                {% csrf_token %}
				<ul class="left-form">
					<h2>New Account:</h2>
					<li>
						{{ reg_form.username }}
						<div class="clear"> </div>
					</li> 
					<li>
						{{ reg_form.email }}
						<div class="clear"> </div>
					</li> 
					<li>
						{{ reg_form.url }}
						<div class="clear"> </div>
					</li> 
					<li>
                        {{ reg_form.password }}
						<div class="clear"> </div>
					</li>
                    <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
					<input type="submit" value="Create And Login">
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
			</form>
	</div>
</body>
</html>

templates/success.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作成功</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
</head>

<body>
<div class="microoh-main" style="height: 100px">
    <div style="position: absolute; top: 20px; left: 20px;">
            <i class="v5-icon v5-icon-right"></i>
            <span>{{ reason | safe }}</span>
    </div>
</div>
</body>
</html>

templates/tag.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ tag_name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}